[[SymEngine]]
arch = "aarch64"
git-tree-sha1 = "54344a6204e396db2f673c9d0ef0a868562730e1"
os = "macos"

    [[SymEngine.download]]
    sha256 = "46937e6f133c5426fbce29b3925da51eccb46725840797cb379a38c7f4f64397"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.aarch64-apple-darwin.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b98c7efbec2fc748ec7477339b643f342f4bb641"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "6ec6e1bcd7a24ba940668d26005b255e872d1712ef9c8a8c3829845879577970"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.aarch64-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e7f712c8de29468ebde2c5dfefe7ba13c1bc938"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "cd422ecd23a3058a2475fb15912dd81a19ba7704c45cd5af673d4526c2c84305"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.aarch64-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bcba6804b87fefd9f5310092f86b16ea0b678087"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "f9adf2179a18a53cd1d7f7413ff126805fb89e78dc67aa0412b37297944aefb0"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.aarch64-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b981f46930b5b45f8fd638f10ed76719e85b936"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "c992126f447adab2d84a4b3db8bb3c92fcba16571cf248fa252c3a17a3f97ea4"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.aarch64-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c333f9b9455916472428c37e82723a3aaf327901"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "aec7d1eac3a90a1bbc40eb8891681b5085a8d65e27593fea556738ee0f839cb1"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab0bfa56e1b561fc345f6de809fb1312ebf8caa9"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "1efedd7df2b67c18c0734cddf87bc32d753abe6c549e14ba49845f290e469f5c"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "89713e462935777015ce6e88cddfc768c1e2f6f1"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "505d05086821b8c1c43e1c1545913ab8ec8510ba2f5ac322cd919e729939e058"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f338dacb5baaf4d5d012ef543d0849de271f8aeb"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "d32ee0e6f2d91082f46cd7feb8353160f6c1834228ee77507018a6e1360de63a"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c02e92df034b9bf1e5f51b71b743a7dc3a9373da"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "64a77d6a0f9ce1cd4fa611ff9860a7dd3d9ce64b81be748eaa81b33a05cd374d"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a1be07654e70946961cc6eb363f98395ec89763"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "9addc4e41f92420cf09007f4b543038eb7f25e60d0f183193ef6fbbbd06f4a91"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ff7d4a6380cb76cf6cfa5c1a71fd18a36094975"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "bccb59010293415bd54c2c55530c603cbb474e7e1f96d2e21a3c53fd2daa7d3a"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7fb38896b067b50173e12e8648cdf82b5095de4f"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "f6b8cd0d9bd41a62074fce56027275d7bbe561a5496ab9a98969e5e3d8781db3"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b5bd0537a0cb46c8ff9fb6b486ac3f1163f155f"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "3065ddc22f24d50e2d6ac4b87780f10b3e97346166c150cdb746f3631a8d9127"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.i686-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77a16696d4813cbcba24ff60c0faf6902cd9572b"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "39213faf55afe801349f93fcf563bb686efada56d1e2a58c7ae72268111a9966"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.i686-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a81bf5d54055581d90b933d57c8c4b028451b036"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "42deb9abe63c5557915d65ee4524035c2e61dc7caae8cbb84182d4166afa92eb"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.i686-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7718aca1a46a1176ab453e4dafa5c63e0cf2a440"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "7cf60d85f0f105b192e15f8895af5cf69d33832ef696b217ba69698155b5b115"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.i686-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c658cdff1702e9f64f9d80263c204164ade0a62"
os = "windows"

    [[SymEngine.download]]
    sha256 = "c15be56062fbb741541192f0c5b6a077e6085f70bc4de9648420c16ffe70b344"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.i686-w64-mingw32-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd0b71a19f87a1e001508ee0423e8d7734d52a60"
os = "windows"

    [[SymEngine.download]]
    sha256 = "bf2caff5cfcad0c424303dd3e826aa034298a8cbf4265b7fccf36d2016a71015"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.i686-w64-mingw32-cxx11.tar.gz"
[[SymEngine]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6fc6e85571f207d24e899f1515241b5328616118"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "c2479d5a40e21fb5757c68c70b6f5f1ae9e65c06dff14731c5198da1d31ff390"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c110bf0ba591be35b44997137e98124e54dba8e"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "97c79d6d17ed4256865cb53fa7e4ecb8c57fb728a8e17dc66982e9df2b760bb2"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
git-tree-sha1 = "bb7fd5f6aeaf2875082175eec42e555f154d99ec"
os = "macos"

    [[SymEngine.download]]
    sha256 = "5f1c77e84a53c2d08d3c06149b867aed39503e7da5e7fefced562b3096154237"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.x86_64-apple-darwin.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "51f8fd8b13b0ce2199442d626a3aba6925732658"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "45cc0348598236c818919329d3c918531be5a76bc0cc2925046571305cd7b99b"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.x86_64-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f6d32527ca954a40385c7c6da23f6b6e4dccfd1"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "9c3f3138e21891488663c78b7c142780ee22c6503ef5bdc8b77cfd9d99a409a9"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.x86_64-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f52624ef443d835231795f6fb2451fea0acff76"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "719c88154f51e58739d4a614a75219660cf67b1a67afb4d7aef8c90a121a7249"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.x86_64-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43d911a409c380b7557dd7042c6e1eafbc871ddd"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "2e516dfb029e420752014cff2e1e777bf51317be60895d096867904119cd1eb2"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.x86_64-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
git-tree-sha1 = "b5e935dc9dd946be59038aa8fa8aac9098590c3d"
os = "freebsd"

    [[SymEngine.download]]
    sha256 = "527644256cade9a6662869f61d6d9315c9e6293e125198f064d650a534384584"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.x86_64-unknown-freebsd.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6cc35fb27648c4a3d93c6d988ddd2b63201ed16e"
os = "windows"

    [[SymEngine.download]]
    sha256 = "fcaed6389f9e38949d9ee6bdb72f0fa838b5024099988a3bbfb34d16d8530c49"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "631fca81b02657bf7111d809971990d7984a7ea6"
os = "windows"

    [[SymEngine.download]]
    sha256 = "1889a81e944fa0891fc7a4b8d55e914f47c6e1594f3bd8237b5eadd97d7eba3d"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.2+0/SymEngine.v0.11.2.x86_64-w64-mingw32-cxx11.tar.gz"
