[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3f1b9c7aea27cf07bc90e92d083c589ebd81f27a"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "c0101bc57380aff8fa1dd49ae5f5854159e3be68e37a43954697d76f6dea606a"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d5f1f61c3989fb6073ded60e6cb1c7916f0c156"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "4ce5d34bd697491d0e0aced7b1d34b324fde853b74dc2505c8a789d4ece90e34"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a30d40f38c7147b673b087f6eb6e6279f59a49e5"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "452ff4d1ccd2ee7da0f276e8d2927ee332e0e8ccebbf736f1ad98dcefa5176d2"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.aarch64-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "714e1b57dd913614097b2f32bf8fd8c60a07c55d"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "40650a5213dc6573bf299639644f0d470313b599624bfc53288b6a4dcf0663c6"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.aarch64-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d2376a25679600124a247d440b141a85d199929"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "58a1320dcde8356daf8e9a8a02bf99ae898bb97f2916d6edbf859e90693d09c8"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "518afb07a521f6f838e713d99f4972672106f5bc"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "91b36d1fb61026c80c0d9ce125792e925a83ad83f6fba78d679f1ffa56c9675a"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "456408b286724a205c4d7912d26ffb7ec53a2814"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "06a0190e4b54c1d750df4d8f0165873e8db91429463d5319650f087fc34b5d1a"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f44f77191dbcca074fbebf56e5f3f072d7b428e6"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "7895bbedd5d36b2e6453dee8edeadf3526ff1f3f7083a0ed44fe849f9643e662"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "423facb7489a70bbcfddb08fa11f22e75eff3950"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "c53030f96fe96af0c0c3371caef3c829b16d323b4c9247791e7e4dd95e4cbc18"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.i686-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91d41e5376d9b3ca1e7751cbe966026fe75e03d8"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "6474c9f2608bcbb9d99f7c450c5b7843850bfb0754cd773eb10c0cb6bcd9161a"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.i686-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4790a83a1644b3bc2992d702dcccd0a3118618fa"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "8687a65eb8b41b3cf7cd34c0325ff0ae0ff9b47b6ec117dbd39a7fa674a50099"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.i686-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b1b51df2c0a2c0c840a564a1b3afb5d81f58f39"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "b628c62448b3bcc62cf55a3ba7acb24c05aa96a8925d58dbe81d58fd43e800f7"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.i686-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65c87b37fd2cae197814a57728e01ba79a068483"
os = "windows"

    [[SymEngine.download]]
    sha256 = "bce2a8b93bb5644c820d6ed36abebfa57ebab618aa1c7e16bfa8dd77fd251aeb"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.i686-w64-mingw32-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db76731d3a0534d2cd7ddc4ce53f13bde7e0ae27"
os = "windows"

    [[SymEngine.download]]
    sha256 = "0cb56a0b4fdf2c7195a91be59564cb526ea758989421d858899f511c0e9b0e4d"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.i686-w64-mingw32-cxx11.tar.gz"
[[SymEngine]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b5148aca14798088dfb7e391f06818561d31b99"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "b5be69a7169fbde6e6cee3b57f41b37c9ae96cbce2d0368298a10b945d3b14c1"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a2dd37c735f200086fbee4731d87d281b8e4d73"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "9ebd05c41b33944e08bc0baabfd43c524b157411853b86736b833918093f87ac"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
git-tree-sha1 = "4c4ef225b9c1d3744a40be9c5b8f8ab77f283f45"
os = "macos"

    [[SymEngine.download]]
    sha256 = "9841c5919988679f1ac5df86dd18b5692ebed439bd436f2ba77ece156abf99a5"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.x86_64-apple-darwin.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4aad8c258a43bffc4a39417533729aaf73ff2e55"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "77ebdce1167170fba3fe5c832e9ab4a0f92e8170f676d54c18fd8a3cf249c633"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b39369e7d95cffd83f787971f7afa9eceed9a84"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "3749a5c69e708574ec870991749e78e7e2408074aba2ef520d7425e013ade122"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39a74e351b9bcc42079f544bdd370236035917a6"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "e3b91842718136d918111d5092006d52f2af76404ce52eb2b122ce20befe5df3"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.x86_64-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "862d2e727733c924c456a071aa243f5410b1bfb2"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "72e3a28d077960482cf4528a69e20330e5b5d88813f61085cc2c08ac81e6b1f6"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.x86_64-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
git-tree-sha1 = "7d4b0b3f87eeea43285a143a63610b8e3d766342"
os = "freebsd"

    [[SymEngine.download]]
    sha256 = "aa2624e2e68b2934efd27e82214654823d9568f096db12dc89aadb1d26f8d2eb"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.x86_64-unknown-freebsd.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7db32f95b870bceb7bc2f0e358b6cbd20aa1a414"
os = "windows"

    [[SymEngine.download]]
    sha256 = "3197f2667be954ac63beffdf9adb8c88709db7349cda9157dd02508a6b1e6624"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f21ab20c86dd8b260f02da35360a6957061c908e"
os = "windows"

    [[SymEngine.download]]
    sha256 = "f53167b862690a5df055326ce16ce6f2842e19120dd03632c4d215eda5cb172b"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.7.0+0/SymEngine.v0.7.0.x86_64-w64-mingw32-cxx11.tar.gz"
