[[SymEngine]]
arch = "aarch64"
git-tree-sha1 = "c7a65870c7e948bb225ba6f05a482223e27b2a9d"
os = "macos"

    [[SymEngine.download]]
    sha256 = "dce73ecdd8f9f26b854e2584a84fb2d2c8216de338f757d8b9e779a9e8d2e0e1"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.aarch64-apple-darwin.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c77d8ca2872e254eefd6d1829dc01ca0d8205380"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "c56652e647c9dcd379a3cdf58e8324c4551c97668d567bdede1790539a3aeee4"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.aarch64-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0c9b6ea95567689e593c0376f37f325e105c5c0"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "6e31ece7a9540b416c1d3e342170d60507a7c1614073476c85c1bd944153aa8b"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.aarch64-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49d3fd7403b4a6ce54106e0d7a5dfd9fb67e17bb"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "f34b535f1fa044c1917c0fe892e2f19a7c06102783fc173d6e87fe44213f3d1f"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.aarch64-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0a28f642fe460c8a8e7478f67386e5372fdb563"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "319a92708cc3511e4de4964565c0a2df2e674e62b550aabf2e170e7e355ca38d"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.aarch64-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "572082a1e59b02c9768c3b4d7f707705113ea89f"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "474187682eaa129b5ee0b0aa3c1bb9f1d2403488edc682dd2122283d9bd7bbe8"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66772ec555800b275ee9054a929faa76dee7a992"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "7b888c886183c2c1e805e566853d870cf4f96c972b155754681f643b7a7bcb76"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d466edbf8f311bcbdaf2060b7cbf5abfb7dd4b9b"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "892d7d7f5b1d22c80cf8e4bf3dae5bb1d34d5b3dd76af493314b25d8fc1facf0"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cf911163ad3ad76ed9754a97a70b7009510b4627"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "9220887031a26a5094006fe1bf2b55a294b4bb22eddc3596b30b505d82ba0d98"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f875d9c1839a9086aa528fc00cb5331ec6a5f9d3"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "46c561af48ca5f454d919e8155567745dec9f53344f1c8cea84762fcf81cc7fb"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1d7015ac23a3af6428e815a2958b870b69c221e"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "80a44cdf60df0b464c860299d13490beb01d10ecc4caa0f11cbe4f0b62ed7506"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b43d135685c5181d4cfecdd53da975f1e26bdd31"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "f875ad5dcbac4d24f5048d4b268eceb98a41fbe0aad82e92150fd05f5e452190"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e251df087f9114ec9f04ed76cc8c24957a65f06b"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "39bf0c4c4f3e0dc2868e33959fae9fe0f5f967c6c1cd37461a5b3ec9fe9f09ef"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c51e46f1e5e5726b3ed5c043e8b577c74324b89e"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "8db84bfbe33041d33ca6a9665cb8a9b62c66e2f8228245a95f2794e791e11b6b"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.i686-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9f3fd74103d66d8d0530eb1e5bb050439d6d265"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "c43e0aa4497b7873da1f3ad88f144742b23e83988864ea32322a39db70d6c627"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.i686-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84ecbd5bad0ff3b56dce867b3ca2a8120b498450"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "0b5a7947d6e6e420d7b91a826021af86ccda9328981eaad6d30cc90e7bfebc6a"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.i686-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ea19f0fd883893581f212e580679119b30951fc"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "6d963e5d700a3919fb4a94ebee1fc5abe8a33d7c0045348b58f5d44b3211b1e3"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.i686-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8990f79cac601c8eb26d170e659541c5ba9fe4f3"
os = "windows"

    [[SymEngine.download]]
    sha256 = "2271911986177edf9d6507baf45105fd4955c5890b74944f93cca9ca52d2dd37"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.i686-w64-mingw32-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3c0b3f3f6edd68d3470e2c45752adf6d8f56cc6"
os = "windows"

    [[SymEngine.download]]
    sha256 = "37e601ca3a9d5d0081029801b910b1468ae6cb37e9bd5156071f7a5ceb720b0c"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.i686-w64-mingw32-cxx11.tar.gz"
[[SymEngine]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e193c7eb3112000d5c2329d8205fc3efe36b90db"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "45c1306fd03a2fec6cc129c58ea90fecd882722eba87484c49cf835cf84728b1"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc230f14b11ae5f7d2ea3aab38a7c2c228e4b4a6"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "8f5ca382d10617fbc27bb8723aee1718bffe568a57b4609fe7b19bb465b3dac4"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
git-tree-sha1 = "e0996496d103fdc6d288ccd029b6d880c83495f3"
os = "macos"

    [[SymEngine.download]]
    sha256 = "1d21327ef8821f01a1be2ff0a3ccfdbce15bf94fe222061d8fee291cb5bdb7d8"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.x86_64-apple-darwin.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e2ee8d04701fd4dfe90de6f64f1eaae207b4d12"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "5c1e3e8d15cbfc6c76a69e487058421f9b1b7ac2f2d0e0e3d87b124d3994a2b8"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.x86_64-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20d7585c7f95c7c05eb546d42515ac4a5a6824c9"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "5ada67f0e2f93209cf9fc6f80397869827f0649bf78bbfb57f39bd2f13c3fb18"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.x86_64-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c97768239870831ecb36457473aa8efb53ac7fba"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "a200d361033b78421397546d828987487ed5baabe8e06b5fa5fdad8bf129e2be"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.x86_64-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca4e8236050414256d21d1e9ff2d24bc123aba17"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "eb5a5e2763ceda60f46369aa4a77f8e97a4250a066231772a4bb68f01fdc57f8"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.x86_64-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
git-tree-sha1 = "33b29dfda0d0a8856b60527b02f31b6ad5deb4dc"
os = "freebsd"

    [[SymEngine.download]]
    sha256 = "262f57c49cfc7b05e4972c1a9a1d7935e8847a11c32de472427e03e8c3696d58"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.x86_64-unknown-freebsd.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f848db268553d3ab60c7f7966de307f4d002a58d"
os = "windows"

    [[SymEngine.download]]
    sha256 = "0f9d943abee921f67be42c7d9d82d7d076a3f7459838c4c4a2b3d44c976ff4c3"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70b8563b2bfd8e10403c8daa4c047fc35ee8cc42"
os = "windows"

    [[SymEngine.download]]
    sha256 = "23b441d6ee96bb8c5f2c10c130b36c60044885f6f58226b51e3a06d62ac08164"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.11.1+0/SymEngine.v0.11.1.x86_64-w64-mingw32-cxx11.tar.gz"
