[[SymEngine]]
arch = "aarch64"
git-tree-sha1 = "4a5feae2611e84ee6e9b9a6a0901c41d9dd7d864"
os = "macos"

    [[SymEngine.download]]
    sha256 = "d2fb00429657d9615e9ab76cd8a66ea2240bdfa31080d2e59111d793d31d81e7"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.aarch64-apple-darwin.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33f06cde7d32598252b678c0601507129494daae"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "d2170527c7bd8c8fe6d46c4423e5208f25e62726dfe97b556282d5e08a8f09a0"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa56a397133f0ba9c02e7ccd0c0e1cabd432736a"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "15deb421c7a935373ccfce3dfb043514ab50283e4b584ef86bf5db29b6c733ab"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a4aa458b9594d44fc9dd9abfa7c5ad6b1cb1bae"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "c3114b628beec72129bc4e45076329341e0ccc32543fff10bac3dbd91e6f9cb0"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.aarch64-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b01fed18581eea4a18a297393b08e641e7d6d681"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "709f32c4ccbc16fff0d1269751aa5bb5d7db8d65ebc7852f7f80f0dcb763871e"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.aarch64-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3efd1aff86d2b3d73cdbc194f7a8ff3716fd1edb"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "f75d7472cbb1254b4945ee91789a4de488562e8e0b7dbc918f7bda6a799145d4"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc737be2c755298fe7fcf21331aa4af4f09dfbe2"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "19c6056b9ff10aa33a94f987be89cfd37d57e3b2dad068ac593f4fc3132ec065"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eba443cadf9697852b9c2d85d287a5ac4ca2436c"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "7950521e7cf39d21bbedf0035a40d712c0c1b1e82a79c4c3c58071b97c2d4705"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ecb9607640555d2ed71465bdd594b7add81d0c1"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "7ce43ac3249dc5efb740492b1be446a97396b30ec7fa7ee800a224df809b8bd0"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "076a9b150fa2618e51c76820c7744be061278a9c"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "66ff0c76800d8cae0a9715b1fcf59e5f4dd8d8613fc12c0b8763855b2e02738a"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82cec7586bcef5a9dcf5a3a3ecfdc6d1736dd471"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "8e02e2c978481a80f992a8ffb934c3a46482250b3327b4d5fb862c958c7f4305"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6b30d599be5a60f5f88583a32e7769adb7e938a"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "c6945bfb7f7c3be30d1ab223e469c0b91e3d783b74dc5870f44cbab561ad74b4"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ebe88b6a27b5a5d0deb17c75a6bccb7384b42c0"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "bd6be8d3ae01da22128edf6b191ff89e25900725d5416cc24f8d4d95d1b9acb1"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "687a9ec2244b049846442ad8345d11c3d8b979fe"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "c6bcf758102e5675dfd06d0d175f512a39b5d277de5837938c7817e9267897fe"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.i686-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d202184e36e0bd5a6b59ef36ace2cf967060250e"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "83e5ad22681db634f7bcf65d1242c2d772dbbf04614267219d9fa404e932e3d8"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.i686-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e66574971c8343af6fc9bd5e4c8c763af28e200"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "60275dd78870144003d9ecfdd7e323eed63f09fc51df324378a227c7317c8355"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.i686-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5313a540af7ef6a06339bbd1588f4f574185479f"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "00107f99e2164abdb411ace4ac4e7c90f8a3b79a390c538823f4f3b59fcee47a"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.i686-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6adb874a6ff2c1d49e266b9458ad2d72b6651f07"
os = "windows"

    [[SymEngine.download]]
    sha256 = "411155992d91747fa2a952c1821ddfba228f350c116755c7f2c6c59cea5dc802"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.i686-w64-mingw32-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ab332f40a75b7f3c0b2fdf73fd7069f0fd34435"
os = "windows"

    [[SymEngine.download]]
    sha256 = "96ea1668cab315855ce9d7f39499e970e884cef9b6d193b8ac3715e4b005e059"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.i686-w64-mingw32-cxx11.tar.gz"
[[SymEngine]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b36643b538f7d6e395be53c0337081ec82f32eed"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "3b68e475068498f64ff649f001f1fdae3ee021d4cea08c863da16e9b9859cae9"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12079a24a2e044e036ca4e996050843aa9d3439b"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "c4203a5bc38ffe3a47fa7d584ef73a199cc35f2351f4aa2baf8f514dd5267ada"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
git-tree-sha1 = "5819bb846c22672aecd1ee3d64f7afe1e92c2d6a"
os = "macos"

    [[SymEngine.download]]
    sha256 = "289ddb7f96df09da5a71138ac21dffd6e8d07cae5bec9803aaf625bb324bd167"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.x86_64-apple-darwin.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cf12c2fa66fb5857e2320d4458309d064f96724c"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "9f6f4ff9278733a7c4677b9c23f43a2cf8a1442e25aa72db652c6036ec96afba"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5243f7039224065ffc7da9cdfb620b38ce93538"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "55b6a3af9e5e36833961c0326e476af3e4fd81ca4fdbf472777ca19fe0a563ab"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d62d5c35ed1a62ace1b5fc341a8f4d25fd225dd3"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "59cdc90c996944b40e90b4b9845a0cc645a34f19a37c98e1dc574ee3cf85ab6c"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.x86_64-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1361bdba56e046f1a62616005de6ac8ca6247f4"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "e4b15a18d4fa66fea840994a874dcee0e58400064d9d1f8ad9d9a3b5b80eb56c"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.x86_64-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
git-tree-sha1 = "bcf30083a37d76b5c515effa6b033c216929a148"
os = "freebsd"

    [[SymEngine.download]]
    sha256 = "ae38a923747aa11761139195e4c0a44dee37859d68b754a5a292a859ea0f98df"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.x86_64-unknown-freebsd.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f69332f8b8fc5d08f9463196850dc28017341116"
os = "windows"

    [[SymEngine.download]]
    sha256 = "a3054900ebfe5e09c4807b40696043e18402986c41087a960734d51ae63ce229"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fdff4e9e7a990be5e69fd9b9fe0af45416b93b7c"
os = "windows"

    [[SymEngine.download]]
    sha256 = "d1e0e9b72c71ac487d98b8a24dbeef8cb0c05fe612e9717d91430912460cc5eb"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+0/SymEngine.v0.9.0.x86_64-w64-mingw32-cxx11.tar.gz"
