[[SymEngine]]
arch = "aarch64"
git-tree-sha1 = "2e37e5a8e0548c28e04881d2ed0e24394b159511"
os = "macos"

    [[SymEngine.download]]
    sha256 = "94a3cff58871fb37e5fab720ea98d8569cbcde53906550a315bcb8918ce1559f"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.aarch64-apple-darwin.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "debeccc2c5b3acfa0ebccad34e3498a46873564c"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "b7e47572e5f1194db6ee24fb1bc7fc6a189bce5fe3c8639e50071fd6c0134dc4"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7535c80674b1a8f1e2ebf072e2eace14b68b1f9c"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "26bcce2896337198a2317e6228534002dc11d4ba9e05f78c2d2fb3a3d140639d"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ad458a3f1e92feacea4db3e9e160b6e7590833a"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "81e9e8bc600ac7251c84d6b38b1e320df6c6b016289d95bc54ca4b2562475fae"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.aarch64-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e8074afc3bce235d1b2563cf71c92e82bd2f351"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "74d6e4420403ebb8e5d37175708ce776251090e3246c8e87d556f8c4b6c8ef9d"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.aarch64-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e35c25569b745f70bc74a17e283652317fdc3e11"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "0fd2a5de27ae896b34e615fa9946d4d7f86d13cea20ad2ddb279ff49069029c9"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "444aa7a87b9ed196fffdecd9cb11d1f2fdf1e637"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "ca017b27447de404d930b5068a8bfd3cfbe0464b682763e2e841a2a3a7865e4e"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5edbbf077adb1838f4e3179eb56117f7a88f1bdb"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "0d64a11fb66076a1298692e86eb01e9d7083183381ca585ba3c1b83e7318cb96"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eed947a7b62feb376ca115e9c69090397339064f"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "5596fa4063facf369ee71a3d05cf0edbea6b018d4b4ee55b98872a9096ef4c3e"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "673b28368dd79e8d3ba4802ddb15fbbaf1514a92"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "121577c76fabd448c33c6e1e571e3b30689151c0e8f3406c15de1a9d51ce39a0"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f08f07f9b73cc6256ab4555514050724bf914e61"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "40896076e481f5153b8f64d39f59c59ec7a34562f3feae68dc8bf38113d7c570"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "037de0e4e50ce64cc8ea5e281cf93f844ad6cda5"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "7b65ef3909232595e016aa82f5609384a1f8384fd5e2ee0b5d1dd2a1798acbf5"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c310b83293d313967af261b621953c0043fc1ef6"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "2dd6734b7cf252cf8723a102a6094a09de30ed69b624de2847d782df4441621f"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "061f577d12f1b0e75daa96589cd857959d141211"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "e90972be76c870ffed12ac4c12b2c1f654c0290526dc20e8157e416caf570ab0"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.i686-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b73b977cd9a047227c36720dd11c20c84ba30a40"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "d0833940a251e19db6c3980a603d74c4656f2ee4706140cefefb709831911fcf"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.i686-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e51c181d9cb381ae721c6559952a5c1ee8377bb"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "e3d2424ff9167d330cab2d00d9cc4330867688a50a8ddc71fd860fecc0062ffb"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.i686-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40ec8f127de288eec74961c1099be5767a7b7dd8"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "65453df0608ebc0a36db1b494c8d9c526a8ff7eaedcfe7bb8b79d896940ea92b"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.i686-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "83156849db7f31dd028a0f2991d6e24db6e60329"
os = "windows"

    [[SymEngine.download]]
    sha256 = "eb8fd5e702e55575fb4e0442895b547da4cb288e7df0d0af539160fd7c704054"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.i686-w64-mingw32-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e357228576f9c8ff1f7539197d8a64f44f71946"
os = "windows"

    [[SymEngine.download]]
    sha256 = "a72b7d7416738d99516909bf0fef1492d5bd65228ccdfac30b441cdc54f06d1e"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.i686-w64-mingw32-cxx11.tar.gz"
[[SymEngine]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0653d6b344b5a5d680eba575a89ca506faf75b0"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "20b01338265d1df1bac4758cd3f6419332f0e84615aa1ecd42961927f0cf13fa"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8cd93b1ba5a9f2d1daabb0ab8d3a4f757c1b037"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "95e76f35f3d68aa360e0c2a055234c09e25d9efbe9da5ad346361313fa023f0d"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
git-tree-sha1 = "72bbdc1bf66a1722a793e6fb95d39c18029d3937"
os = "macos"

    [[SymEngine.download]]
    sha256 = "49c9d878d256068c33844c382bf70dc5398063e5917df979b708f0ed524ee0f7"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.x86_64-apple-darwin.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9be862592e281c8e4cf4b4c7f32166f32eb33f62"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "6a1d0bcfe0e08ded04da8cd214e3c794f634daff0852a146bce08b137aacc326"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b99956590f90a608ded76e0757af76a17f8289a"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "bdcf4e2a3e694509abac184a29c466a5aecb068c8eaf6b8c8dc0d57f5682b464"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "860379bbdda4da18715002679cb4b33216cc13a7"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "3c4f1102129e10f1348965f3831368a1359b81405121c96588cdc190970c8d39"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.x86_64-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5b3335df930f7bb58c38022bbb7ee993acac317"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "fbd43a71413de20281179c7008cec1407c507b4f804ff722f12214ca7a5568c9"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.x86_64-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
git-tree-sha1 = "a1041f70d952740f926569aeb92189fc7ed0c8ea"
os = "freebsd"

    [[SymEngine.download]]
    sha256 = "fd539f3d092cb693f4c61955be4eb0144134cf076efffdb45cb9d847b788bde4"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.x86_64-unknown-freebsd.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "206760427c3db814ca5db9fe8a10b6c657e0ff25"
os = "windows"

    [[SymEngine.download]]
    sha256 = "d99b83e1f0cd99ad685d8f34860266bba51d235b661417272c46e6781e87a9c9"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4285b91617e6f3ad440b3733f96927e7601ba3bf"
os = "windows"

    [[SymEngine.download]]
    sha256 = "1f0725fa855ece7f355a6bfbcfd4ed32fb5c3ad7eccd9e36458eebbdeae4f5d8"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.9.0+1/SymEngine.v0.9.0.x86_64-w64-mingw32-cxx11.tar.gz"
