[[SymEngine]]
arch = "aarch64"
git-tree-sha1 = "28444baec68047168197980592e0459f6b673eeb"
os = "macos"

    [[SymEngine.download]]
    sha256 = "f1605b9b3dd23439d3639e6192aa1ea956e50dc92c24a233b0abc00e4d0f2d6f"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.aarch64-apple-darwin.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6134f59ba101c77b09918c17e95a648ea216eb4"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "c3f2aeeba8cf93a4e80717f51b3eb5571a73a4559ea78475796a40ebbe9e5cdb"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.aarch64-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b01268939ad76c09d5662d012d864b3673328034"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "f66d02cea66e81fedee744d48d28fe96afb44477fb69bdd44f32dd8120ed298b"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.aarch64-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d809499f1fe46bffc884f9b18552288ea547be2"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "292e0e4ce206dd039a5a7896cb4b2242db95d03aeaf5d2137936f4a1ba13eb5b"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.aarch64-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1fdc11d642a32eead0db15f9f46609aa09143a8b"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "4f6db1659b7fb4cb336f48cc189b5e967ad9d8ada6adeaca8b080a0c8cadd375"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.aarch64-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cfae3b2965114c451ede4fca2c4116e1c66931d8"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "7ce3efeb3ea42e4a9609be8e682603a580e12e407a0b458dde9bbeba608d9b4c"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa720e7904a0e5aacfaa58216ca002d6f4c97bcf"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "ec53a61207509d154c874c22e3dbfbbe8745a1f0f5dcdf14a225e1be23e2ace2"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "04f6e7bd3b8c5bfbd4c6534d106e62066e29681b"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "4183022ebd572eae3f555139af7beb06691dd8161f6d5f26814d6e0c285c5d11"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97a6c70fd4a1409a0757d9bfd84ae87f4806475d"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "0f934f69e216b5730538c0d4ad7970abf93f77e925f6007890ec80a5bf1278be"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "596aeb5d11fac1d11361bc4a0b7b77da834bd297"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "e8579c712a89a6f2809ca0114d329048b9f913598fc798b21551695167fcd81a"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f0ffd2f693663a42e2693963c3e579b98650aa2"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "d7e0b3a81bd8970c6ade61279cdddbc8f5a20c2d546834d67bc2c8000c5e9dca"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69ada09320c317f6f2a17c28f26f338fbbfa8a53"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "d7ba63e60020ec082728b5132ae759df3e326e64fbff151473eba32ff7895ed0"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f0408e9eaa87bda8de0ac17f49bc7bb08f20076"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "06044cedfe13b5517549d6bf2ebfc4b030f1ffb5e6f28f803e3ae2137707d074"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2c4d414c7632068e0027dab74a983a3152c4d764"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "edd9ac1d5b533d6c06ab08f1aa65ebbb69c2bf8979f20e4d562e562c4fbc037f"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.i686-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09eac33797fb4ba8618bbc8f6c362cd4ca14a210"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "3655492733361e6880de19c3e879939cc5babf9552a9b7fd19ad34f1b3852481"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.i686-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd290f85510bf8a4599466d109fa224853aa837b"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "c42a13f1a684eb278e6fe944edb51f541d5a39e2c5f7b4dead38b4bb63952834"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.i686-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4cd9e93faaed9bedd7267a621600d704db8ab09d"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "24d9168725c73e0450ae97d11be4e8a7b45ad17271a1adaaa541802119bd030c"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.i686-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "530153fa2983c99651ea513c3acb2dd4d038efd8"
os = "windows"

    [[SymEngine.download]]
    sha256 = "aca2ed9b55663ed573396e3d5a4ba2e7df123973308bcf0ce202f8dc3daddda7"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.i686-w64-mingw32-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c636e1cc657815faa6d1623ee7a8e96ed2a5660"
os = "windows"

    [[SymEngine.download]]
    sha256 = "0acdc47db6ae108f51640b23d85d86c4d1179f07dd82ff5addebc16363cc6b04"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.i686-w64-mingw32-cxx11.tar.gz"
[[SymEngine]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "060103a8458b07d0c27251aaa414474030e8e117"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "8d82e2d7a984ce3f1b11124be67cd92962b2ff2085c770258d59e314f9e362d0"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3beb22747d7efe1c93a9c3028d4c0e309d7b8b07"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "8506eb33f86aaee51ccd8cf3bee44c1ef8b1ec084ef6080698124f0401e92ffa"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
git-tree-sha1 = "1bd603286dc94cb8208d8f5abc06c57437d8055e"
os = "macos"

    [[SymEngine.download]]
    sha256 = "9a5c4a1ba3d4eb23ebad885a58c497d55c5b63325152452658861cb898038e9e"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.x86_64-apple-darwin.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ba24419e52afae63ae30bb8b127cbfc80938946"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "f9c40f67b4bd60e9b431e795aced030b51242d9bac9295b19e6c89f296b73201"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.x86_64-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8192a4fc347dc5d7c32b3acfde7af2074fe436a6"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "e07ccbebdd5045924b75f955339adec4981022ffb8396b8a40a533748eed5465"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.x86_64-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "75485c58671a92750e204bc64f3d2b8a5d509281"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "65609d3309a6024f1d8b85d0ee8606a5e81b88d62ca84412d75a15b5c636b653"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.x86_64-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0723be23ae8ef301c04150a0281256034248c3b"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "c3a0e5c15fbf5e5a1d4aff0641e60514bad48b03d239ff92deb49b7629bdfaa1"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.x86_64-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
git-tree-sha1 = "2147728ca5c64ea39e0afda52f395f64d6a8d208"
os = "freebsd"

    [[SymEngine.download]]
    sha256 = "000b6db38253672bd6fae0729d0afcdb2040e9d663dd4b6fd247cba2c35b125e"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.x86_64-unknown-freebsd.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a0c8f6986d02fa378dc22a3b2cfca76a752af1d"
os = "windows"

    [[SymEngine.download]]
    sha256 = "8b4ba6baaa0c649ade76c1aaefea384d49005d2ccea10c292bac3f9ad629509b"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "635e58d3b6452a234dbf29dbac9259f2a3f7947e"
os = "windows"

    [[SymEngine.download]]
    sha256 = "23032eb6edd428abe3ca9c135937312315a2e8dc5e0ad4f0c393b87736e63f58"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.1+0/SymEngine.v0.8.1.x86_64-w64-mingw32-cxx11.tar.gz"
