[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5bfa2301ba9c342e26a60a3c249c7857a8e0b089"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "62d316cb011b08207bbbe8f4ee719a300d9b22b256d11e6c71da9a8a62625bb8"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ebec40f726e51307d1b9ddc9a9935632d07cf7f"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "a773306a0a7915ec20eb4a9a9e67521ca80ef9638bda0c5f053221b2e0972f70"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77a850c0a57dfc29e373b143e2a04e9b3b2b083c"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "29eed8b97503d02f9851e6551f2a3bac0f7cb125d5523128cddbcb9c0ecbc208"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.aarch64-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3aba9f6a4a0e37815463851981e57871efda815"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "de4a3e61a7e48679e1048f4f9c470c9a2f10ee9a323a92322d6ed87758be9ba4"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.aarch64-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d7326ec101cdacb147dd4974f019dd245efdba5"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "b6c910be4809d719a08154587d04709c84af8bfe989fb4950ce7d9d81d560821"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6787afb819f5a795398524fc72d35199752b77e8"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "4870803d161ae559049d68cafaaf050da35fcdd579854fb664832ebf6b6d5c5e"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ac366a480198ec2634b4a2f69dfeff23931303b"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "0fcf7af888b948bca60d0c5478695c709d34e0a9d5470fd49d7cb3309553129d"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SymEngine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e463ca7ad6c5dfce7b5f0c4a457c2f6456c58a5"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "29711fb26a54f9d6db40730897a2bc42adf2294b2473048979882daef6eaf276"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c98b718315edcfe552936364db13e74ba25dfaf4"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "27330865dabf037d0763455523e66126fad1dada1b9f62ed7e2c002cb084de63"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.i686-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80087b2e899462bc02ee1eb3396d13b908d76640"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "8e828e77cf3a7d852c509fa020be5861af65c879d58074c1a70435d9bfbd8603"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.i686-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60e32de4205d08bdebd17d0fcf6068593bddefd9"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "efff579c15fcbab14b506077d6517361d754dcdb4f48fa4e54790c8ed9b21b83"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.i686-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81dd7f0196aa1c42f93c1cc1899a231f18b65623"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "a57ff4c5d91242ef09cac68fb751c87305e09308303e2d816ce6e36b0aed2849"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.i686-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "272bce250ae8c11e3c38fe9c5a97561c23c3c198"
os = "windows"

    [[SymEngine.download]]
    sha256 = "95f7d18af41e4bc08384773e02c63227e7925421a1b65073393ec72a72cca38b"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.i686-w64-mingw32-cxx03.tar.gz"
[[SymEngine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a9e362e1f443f0542d05fc01c37c18a62a9bd03"
os = "windows"

    [[SymEngine.download]]
    sha256 = "3feb8eda8e74ac0e97bc10858347c0ae917a2e98499624b4e9c1e5a1369e4d42"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.i686-w64-mingw32-cxx11.tar.gz"
[[SymEngine]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee8ad6f4d94a4cab26cd490bf8cf02921776d12a"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "09328f74dd326df10c0ee50098123c60504bf1e9c721dd400f259125575e8a19"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "240c04070563683e9808d1bb4ba2619cae08abee"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "babd2e9155012786edf78a721642495915aff3e1ea1ce4db1f571243e2caabcd"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
git-tree-sha1 = "12763e79f578b35c27e9dfd4bf82e9f9f8e6f90f"
os = "macos"

    [[SymEngine.download]]
    sha256 = "86ba588258febe822bf4f512e32cbb01baa12dbd794b2770a515985c6df511b3"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.x86_64-apple-darwin.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84bcf843bf2d9f9b9d0222d1a7a40a52a1fe12da"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "92398d5807fe84a385e354be460becae66e5b63c21052ca28e36303e732bc128"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba7d931a7fe8b6f27199040e456a4aab6264f0d7"
libc = "glibc"
os = "linux"

    [[SymEngine.download]]
    sha256 = "25ee8e529faeb5983443ab7fc70654b37a69d627afe1f3a3899ceee6667ea6aa"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bbe8f85aaa0e29f478d57dc1cdfb0d79fe1ca771"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "3c7144ea64e3897ab6f6b2e7ef503de9621fd22287528edc2f2d976a5054a344"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.x86_64-linux-musl-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7131cb1b63d891fb87c072d07e804c3521b9845d"
libc = "musl"
os = "linux"

    [[SymEngine.download]]
    sha256 = "60efe47cabc8de254a7b017860b2d6fdd7747025d43162b0282ad835e086390d"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.x86_64-linux-musl-cxx11.tar.gz"
[[SymEngine]]
arch = "x86_64"
git-tree-sha1 = "0f582f8d9db0441da4e6d663d508a337b7024fdc"
os = "freebsd"

    [[SymEngine.download]]
    sha256 = "d89ea7f55070eb7d93d07e00124af163cd3d234b96315d168098da0534fe8f00"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.x86_64-unknown-freebsd.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d342a940da59a4a8719bec683c77753027321f47"
os = "windows"

    [[SymEngine.download]]
    sha256 = "e75db0a4e3d717968a22793140b10e0ca77804236f15dddfa90b2a0ffb902314"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SymEngine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88602abce4a960cfce41becedbc0faeeca0da28e"
os = "windows"

    [[SymEngine.download]]
    sha256 = "a19163c51cf6247dceede4a516919fa108113edbcea8f302e18d3a4aa491e10a"
    url = "https://github.com/JuliaBinaryWrappers/SymEngine_jll.jl/releases/download/SymEngine-v0.8.0+0/SymEngine.v0.8.0.x86_64-w64-mingw32-cxx11.tar.gz"
